# Generated by Django 5.1.6 on 2025-02-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doremiredo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='model',
            field=models.CharField(choices=[('cash', 'cash'), ('m_banking', 'm_banking'), ('card', 'card')], default='cash', max_length=10),
        ),
    ]
