# Generated by Django 5.1.6 on 2025-02-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doremiredo', '0003_student_course_alter_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
