# Generated by Django 5.1.6 on 2025-02-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doremiredo', '0009_student_contact_student_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='birth_year',
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
